version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py migrate django_celery_results && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A core worker --loglevel=info -P gevent
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=django-db
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
    name: app-network